# This rule is not used by the project v3 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to z0.v0.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: v3
    app.kubernetes.io/managed-by: kustomize
  name: deploymakerv0-viewer-role
rules:
- apiGroups:
  - z0.v0.com
  resources:
  - deploymakerv0s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - z0.v0.com
  resources:
  - deploymakerv0s/status
  verbs:
  - get
