---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - z0.v0.com
  resources:
  - podmakerv0s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - z0.v0.com
  resources:
  - podmakerv0s/finalizers
  verbs:
  - update
- apiGroups:
  - z0.v0.com
  resources:
  - podmakerv0s/status
  verbs:
  - get
  - patch
  - update
